### ISSUE TITLE
Posts not appearing

### ISSUE THREAD

**Issue by iginsider** [itsmingjie/ganymede#21]
Posts not appearing when activating theme. 
Example:  http://thebluedrift.com/

Unable to remove @itsmingjie from header

Currently running Ghost 3.41.5-0

**Comment by itsmingjie** [comment]
Hi, thanks for the issue. The header `@itsmingjie` is set in https://github.com/itsmingjie/ganymede/blob/main/partials/header.hbs and not a specific setting. You will need to fork this template and modify it by yourself.

For posts not appearing, the homepage only renders the Page with slug "/home", because I wanted it to render a custom page. If you do not want that, you can take a look at https://github.com/itsmingjie/ganymede/blob/main/home.hbs and replace the contents with the relevant section of https://github.com/itsmingjie/ganymede/blob/main/index.hbs. 

Closing this issue because there're no immediate actionables in the codebase.
